name : Hello World Workflow
on : pull_request
jobs : 
  say-hello :
    runs-on: ubuntu-lates
    steps:
    - name : "Say Hello"
      run : echo "Hello Wozrld"
    - name : "Say Goodbye"
      run : echo "Say Goodbye"
  create-folder :
    runs-on: ubuntu-lates
    steps:
    - name : "Git Clone"
      run : git clone https://github.com/nanto-potgieter/CICDHari3.git
    - name : "list file"
      run : ls -la
    
